routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::get('/', function () {
    return view('auth/login');
});

//Route::group(['middleware' => ['isAdmin']], function () {
    Route::get('/package_types/grid', 'PackageTypesController@grid');
    Route::resource('/package_types', 'PackageTypesController');

    Route::get('/main_offices/grid', 'MainOfficesController@grid');
    Route::resource('/main_offices', 'MainOfficesController');

    Route::get('/clients/grid', 'ClientsController@grid');
    Route::resource('/clients', 'ClientsController');

    Route::get('/stations/grid', 'StationsController@grid');
    Route::resource('/stations', 'StationsController');

    Route::get('/payment_modes/grid', 'PaymentModesController@grid');
    Route::resource('/payment_modes', 'PaymentModesController');

    Route::get('/manifests/grid', 'ManifestsController@grid');
    Route::resource('/manifests', 'ManifestsController');
    Route::post('/manifests/dispatch_manifest', 'ManifestsController@dispatch_manifest');
    Route::get('/manifests/print_manifest/pdf', 'ManifestsController@print_manifest');
    Route::get('/manifests/manifest_no/autocomplete', 'ManifestsController@autocomplete');
    Route::get('/manifests/offload/manifest', 'ManifestsController@offload_manifest'); 

	Route::post('/manifests/manifest/offload', 'ManifestsController@offload');
	
	/*Route::get('/waybills/grid', 'WaybillsController@grid');
    Route::resource('/waybills', 'WaybillsController');
    Route::get('/waybills/print_waybill/pdf', 'WaybillsController@print_waybill');*/
	
	Route::get('/waybill_manifests/grid/{manifest}', 'WaybillManifestsController@grid');
    Route::get('/waybill_manifests', 'WaybillManifestsController@index');
    Route::get('/waybill_manifests/{manifest}', 'WaybillManifestsController@show');
    Route::get('/waybill_manifests/filters/{manifest}', 'WaybillManifestsController@filters');
    Route::get('/waybill_manifests/filter_grid/{manifest}', 'WaybillManifestsController@filter_grid');
    Route::post('/waybill_manifests/add_batch', 'WaybillManifestsController@add_batch');
    Route::post('/waybill_manifests/remove_batch', 'WaybillManifestsController@remove_batch'); 
	
    Route::get('/waybill_statuses/grid', 'WaybillStatusesController@grid');
    Route::resource('/waybill_statuses', 'WaybillStatusesController');

    Route::resource('/users', 'UserController');
    Route::resource('/roles', 'RoleController');
    Route::resource('/permissions', 'PermissionController');

    Route::get('/test_tables/grid', 'TestTablesController@grid');
    Route::resource('/test_tables', 'TestTablesController');
    
//});

Auth::routes();

Route::get('/home', 'WaybillsController@index')->name('home');

Route::get('/waybills/tracking/status', 'WaybillsController@tracking');
Route::get('/waybills/tracking/trackWaybill/{waybillNo}', 'WaybillsController@trackWaybill');

Route::get('/clients/getClients/all', 'ClientsController@getAllClients');

//Route::group(['middleware' => ['role:admin|staff']], function () {
	/*Reports*/
    Route::get('/user_reports/grid', 'UserReportsController@grid'); 
    Route::get('/user_reports/print_waybill/pdf', 'UserReportsController@print_waybill');
    Route::resource('/user_reports', 'UserReportsController'); 
    
    Route::resource('/station_reports', 'StationReportsController'); 
    Route::get('/station_reports/get_report_data/extra/', 'StationReportsController@getReportData');
    Route::get('/print_station_report', 'StationReportsController@printStationsReport');

    Route::resource('/client_reports', 'ClientReportsController');

    Route::get('/cashiers_reports', 'CashierReportsController@index');
    Route::get('/print_cashier_report', 'CashierReportsController@printCashierReport');

    Route::get('/invoices/grid', 'InvoicesController@grid'); 
    Route::get('/invoices/get_waybills/{invoice_id}', 'InvoicesController@getWaybills');  
    Route::get('/invoices/get_transactions/{invoice_id}', 'InvoicesController@getTransactions');
    Route::resource('/invoices', 'InvoicesController');  
    Route::get('/invoices/{id}', 'InvoicesController@show');
    Route::post('/invoices/cancel_invoices', 'InvoicesController@cancelInvoices'); 
    
    Route::resource('/transactions', 'TransactionsController');
//});

//Route::group(['middlewar> ['role:staff']], function () {

    //Route::get('/manifests/grid', 'ManifestsController@grid');
    //Route::resource('/manifests', 'ManifestsController');
    //Route::post('/manifests/dispatch_manifest', 'ManifestsController@dispatch_manifest');
   // Route::get('/manifests/print_manifest/pdf', 'ManifestsController@print_manifest');
    //Route::get('/manifests/manifest_no/autocomplete', 'ManifestsController@autocomplete');
    //Route::get('/manifests/offload/manifest', 'ManifestsController@offload_manifest');    
    //Route::post('/manifests/manifest/offload', 'ManifestsController@offload');
	
    Route::get('/waybills/grid', 'WaybillsController@grid');
    Route::resource('/waybills', 'WaybillsController');
    Route::get('/waybills/print_waybill/pdf', 'WaybillsController@print_waybill');
    //Route::get('/waybills/tracking/status', 'WaybillsController@tracking');
    //Route::get('/waybills/tracking/trackWaybill/{waybillNo}', 'WaybillsController@trackWaybill');


    //Route::get('/waybill_manifests/grid/{manifest}', 'WaybillManifestsController@grid');
    //Route::get('/waybill_manifests', 'WaybillManifestsController@index');
    //Route::get('/waybill_manifests/{manifest}', 'WaybillManifestsController@show');
    //Route::get('/waybill_manifests/filters/{manifest}', 'WaybillManifestsController@filters');
    //Route::get('/waybill_manifests/filter_grid/{manifest}', 'WaybillManifestsController@filter_grid');
    //Route::post('/waybill_manifests/add_batch', 'WaybillManifestsController@add_batch');
    //Route::post('/waybill_manifests/remove_batch', 'WaybillManifestsController@remove_batch'); 
    
       
    
//});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','station',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
    
    public function stations()
    {
        return $this->hasOne('App\Station','id', 'station');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\User;
use App\Station;
use Auth;
use Spatie\Permission\Models\Role;
use Session;
use Illuminate\Support\Facades\Hash;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Validator;
use Carbon\Carbon;
use Illuminate\Validation\Rule;

class UserController extends Controller
{

    protected $title;

    public function __construct()
    {
        //$this->middleware(['auth', 'isAdmin']); //isAdmin middleware lets only users with a //specific permission permission to access these resources
        $this->middleware(['auth']);
        $this->title = "Users";
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $title = $this->title;
        $users = User::all();
        $roles = Role::select('id', 'name')->where("id", "!=", ROOT)->get();

        return view('users.index', compact('title', 'users', 'roles'));
    }

    /**
     * Get datatables grid data
     * @param Request $request
     * @return type
     */
    public function grid(Request $request)
    {
        return datatables(
            DB::table('users')
                ->leftJoin('users AS u2', 'users.created_by', '=', 'u2.id')
                ->leftJoin('users AS u3', 'users.updated_by', '=', 'u3.id')
                ->leftJoin('model_has_roles', 'model_has_roles.model_id', '=', 'users.id')
                ->leftJoin('roles', 'roles.id', '=', 'model_has_roles.role_id')
                ->select([
                    "users.id",
                    "users.name",
                    "users.email",
                    "users.first_name",
                    "users.last_name",
                    DB::raw("GROUP_CONCAT(roles.id) AS role_ids"),
                    DB::raw("GROUP_CONCAT(roles.name) AS role"),
                    DB::raw("DATE_FORMAT(users.created_at,'%d-%m-%Y') AS created_at"),
                    DB::raw("DATE_FORMAT(users.updated_at,'%d-%m-%Y') AS updated_at"),
                    DB::raw("CONCAT(u2.first_name,' ',u2.last_name) AS created_by"),
                    DB::raw("CONCAT(u3.first_name,' ',u3.last_name) AS updated_by"),
                    DB::raw("(users.id +1) AS action")
                ])->orderBy('name', 'ASC')->groupBy(['users.id']))->toJson();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //Get all roles and pass it to the view
        $roles = Role::get();
        //$stations = Station::where('status',ACTIVE)->pluck('office_name','id');

        return view('users.create', compact('roles', 'stations'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $validator = Validator::make($request->all(), [
                'name' => 'required|unique:permissions|max:120',
                'first_name' => 'required|max:30',
                'last_name' => 'required|max:30',
                'email' => 'email|unique:users',
                'password' => 'required|min:6|confirmed',
            ]
        );

        if ($validator->passes()) {

            $result = true;

            DB::transaction(function () use ($request, $result) {
                try {

                    $user = new User();
                    $user->name = $request->name;
                    $user->email = $request->email;
                    $user->first_name = ucfirst($request->first_name);
                    $user->last_name = ucfirst($request->last_name);
                    $user->password = bcrypt($request->password);
                    $user->created_by = Auth::user()->id;
                    $user->created_at = Carbon::now();
                    $user->save();

                    $roles = $request->roles;

                    if (isset($roles)) {

                        foreach ($roles as $role) {
                            $role_r = Role::where('id', '=', $role)->firstOrFail();
                            $user->assignRole($role_r);
                        }
                    }

                } catch (\Exception $e) {
                    $result = false;
                }
            });

            if ($result) {
                return response()->json(array("type" => "success", "text" => "Created user successfully"), 200);
            } else {
                return response()->json(array("type" => "error", "text" => "Creating user failed!"), 200);
            }

        } else {

            if ($request->ajax()) {
                return response()->json(array(
                    'success' => false,
                    'message' => 'There are incorect values in the form!',
                    'errors' => $validator->getMessageBag()->toArray()
                ), 422);
            }

            $this->throwValidationException(
                $request, $validator
            );
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return redirect('users');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id); //Get user with specified id
        $roles = Role::get(); //Get all roles

        return view('users.edit', compact('user', 'roles')); //pass user and roles data to view
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {


        $validator = Validator::make($request->all(), [
                'name' => 'required|unique:permissions|max:120',
                'first_name' => 'required|max:30',
                'last_name' => 'required|max:30',
                'email' => ['required', Rule::unique('users')->ignore($id)]
            ]
        );

        if ($validator->passes()) {

            $result = true;

            DB::transaction(function () use ($id, $request, $result) {
                try {

                    $user = User::findOrFail($id);

                    $user->name = $request->name;
                    $user->email = $request->email;
                    $user->first_name = ucfirst($request->first_name);
                    $user->last_name = ucfirst($request->last_name);
                    $user->updated_by = Auth::user()->id;
                    $user->updated_at = Carbon::now();

                    $user->save();

                    $roles = $request->roles;

                    if (isset($roles)) {
                        $user->roles()->sync($roles);
                    } else {
                        $user->roles()->detach();
                    }

                } catch (\Exception $e) {
                    $result = false;
                }
            });

            if ($result) {
                return response()->json(array("type" => "success", "text" => "Updated user successfully"), 200);
            } else {
                return response()->json(array("type" => "error", "text" => "Updating user failed!"), 200);
            }

        } else {

            if ($request->ajax()) {
                return response()->json(array(
                    'success' => false,
                    'message' => 'There are incorect values in the form!',
                    'errors' => $validator->getMessageBag()->toArray()
                ), 422);
            }

            $this->throwValidationException(
                $request, $validator
            );
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //Find a user with a given id and delete
        $user = User::findOrFail($id);
        $user->delete();

        return redirect()->route('users.index')
            ->with('flash_message', 'User successfully deleted.');
    }

    public function updatePassword()
    {
        return view('users.change_password');
    }

    public function changePassword(Request $request)
    {
        $user = Auth::user();

        $currentPassword = $request['current_password'];
        $newPassword = $request['password'];
        //dd("1");
        $this->validate($request, [
            'current_password' => 'required|min:3',
            'password' => 'required|min:3|confirmed'
        ]);


        if ($user) {
            if (Hash::check($currentPassword, $user->password)) {
                $userId = $user->id;
                $objUser = User::where("id", $userId)->first();
                $objUser->password = Hash::make($newPassword);
                $objUser->save();

                return redirect('login')->with(Auth::logout());
            } else {
                return redirect('update_password')
                    ->withErrors(['Failed to match passwords']);
            }
        } else {
            return redirect('update_password')
                ->withErrors(['Incorrect current password']);
        }
    }

}

resources/views/users/change_password.blade.php
@extends('layouts.app')

@section('content')
<div class="col-sm-3"></div>
<div class="col-sm-6" align="center">
    <div class="panel panel-default">
        <div class="panel-heading">
            UPDATE PASSWORD
        </div>

        <div class="panel-body">
            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif

            <form action="{{ url('/change_password') }}" method="POST" class="form-horizontal">
                {{ csrf_field() }}

                <div class="form-group">
                    <label for="current_password" class="col-sm-3 control-label">Current Password</label>
                    <div class="col-sm-6">
                        <input type="password" name="current_password" required id="current_password" class="form-control" value="">
                    </div>
                </div>
                <div class="form-group">
                    <label for="new_password" class="col-sm-3 control-label">New Password</label>
                    <div class="col-sm-6">
                        <input type="password" name="password" required id="password" class="form-control" value="">
                    </div>
                </div>
                <div class="form-group">
                    <label for="password_confirmation " class="col-sm-3 control-label">Confirm Password</label>
                    <div class="col-sm-6">
                        <input type="password" name="password_confirmation" required id="password-confirmation " class="form-control" value="">
                    </div>
                </div>

                <div class="">
                    <button type="submit" class="btn btn-primary">CHANGE PASSWORD
                    </button> 
                </div>
            </form>

        </div>
    </div>

</div>




@endsection

resources/views/users/create.blade.php
{{-- \resources\views\users\create.blade.php --}}
@extends('layouts.app')

@section('title', '| Add User')

@section('content')

<div class='col-lg-4 col-lg-offset-4'>

    <h1><i class='fa fa-user-plus'></i> Add User</h1>
    <hr>

    {{ Form::open(array('url' => 'users')) }}

    <div class="form-group">
        {{ Form::label('station', 'Station') }}<br>
        {{Form::select('station_id', $stations,null, array('class' => 'form-control', 'required'))}}

    </div>


    <div class="form-group">
        {{ Form::label('name', 'Name') }}<sup>*</sup>
        {{ Form::text('name', '', array('class' => 'form-control', 'required')) }}
    </div>

    <div class="form-group">
        {{ Form::label('email', 'Email') }}
        {{ Form::email('email', '', array('class' => 'form-control')) }}
    </div>

    <div class='form-group'>
        @foreach ($roles as $role)
        {{ Form::checkbox('roles[]',  $role->id ) }}
        {{ Form::label($role->name, ucfirst($role->name)) }}<br>
        @endforeach
    </div>

    <div class="form-group">
        {{ Form::label('password', 'Password') }}<sup>*</sup><br>
        {{ Form::password('password', array('class' => 'form-control', 'required')) }}

    </div>

    <div class="form-group">
        {{ Form::label('password', 'Confirm Password') }}<sup>*</sup><br>
        {{ Form::password('password_confirmation', array('class' => 'form-control', 'required')) }}

    </div>

    {{ Form::submit('Add', array('class' => 'btn btn-primary')) }}

    {{ Form::close() }}

</div>

@endsection

resources/views/users/edit.blade.php
{{-- \resources\views\users\edit.blade.php --}}

@extends('layouts.app')

@section('title', '| Edit User')

@section('content')

<div class='col-lg-4 col-lg-offset-4'>

    <h3><i class='fa fa-user-plus'></i> Edit {{$user->name}}</h3>
    <hr>

    {{ Form::model($user, array('route' => array('users.update', $user->id), 'method' => 'PATCH')) }}{{-- Form model
    binding to automatically populate our fields with user data --}}

    @include('errors.errors')

    <div class="row">
            <div class="form-group">
                {{ Form::label('station', 'Station') }}<br>
                {{Form::select('station', $stations,null, array('class' => 'form-control', 'required'))}}
            </div>

            <div class="form-group">
                {{ Form::label('name', 'Name') }}
                {{ Form::text('name', null, array('class' => 'form-control')) }}
            </div>

            <div class="form-group">
                {{ Form::label('email', 'Email') }}
                {{ Form::email('email', null, array('class' => 'form-control')) }}
            </div>

            <h5><b>Give Role</b></h5>

            <div class='form-group'>
                @foreach ($roles as $role)
                {{ Form::checkbox('roles[]', $role->id, $user->roles ) }}
                {{ Form::label($role->name, ucfirst($role->name)) }}<br>

                @endforeach
            </div>

        <div class="form-group">
                {{ Form::label('password', 'Password') }}<br>
                {{ Form::password('password', array('class' => 'form-control')) }}

            </div>

        {{-- <div class="form-group">
             {{ Form::label('password', 'Confirm Password') }}<br>
             {{ Form::password('password_confirmation', array('class' => 'form-control')) }}

         </div>--}}

            {{ Form::submit('Update', array('class' => 'btn btn-primary pull-right')) }}
    </div>
    {{ Form::close() }}

</div>

@endsection

resources/views/users/index.blade.php
{{-- \resources\views\users\index.blade.php --}}
@extends('layouts.app')

@section('title', '| Users')

@section('content')

<div class="col-lg-10 col-lg-offset-1 row">
    <div class="col-lg-8">
        <h3><i class="fa fa-users fa-1x"></i> User Administration</h3>
    </div>
    <div class="col-lg-4">
        <a href="{{ route('roles.index') }}" class="btn btn-info">Roles</a>
        <a href="{{ route('permissions.index') }}" class="btn btn-primary">Permissions</a>
        <a href="{{ route('users.create') }}" class="btn btn-success">Add User</a>
    </div>

    <hr>
    <div class="">
        <table id="thegrid" class="table table-bordered table-striped table-condensed">

            <thead>
            <tr>
                <th>Name</th>
                <th>Station</th>
                <th>Email</th>
                <th>Date/Time Added</th>
                <th>User Roles</th>
                <th>Operations</th>
            </tr>
            </thead>

            <tbody>
            @foreach ($users as $user)
            <tr>

                <td>{{ $user->name }}</td>
                <td>{{ $user->stations["office_name"] }}</td>
                <td>{{ $user->email }}</td>
                <td>{{ $user->created_at->format('F d, Y h:ia') }}</td>
                <td>{{ $user->roles()->pluck('name')->implode(' ') }}</td>
                {{-- Retrieve array of roles associated to a user and convert to string --}}
                <td>
                    <a href="{{ route('users.edit', $user->id) }}" class="btn btn-info btn-xs pull-left"
                       style="margin-right: 3px;">Edit</a>

                    {!! Form::open(['method' => 'DELETE', 'route' => ['users.destroy', $user->id] ]) !!}
                    {!! Form::submit('Delete', ['class' => 'btn btn-danger btn-xs']) !!}
                    {!! Form::close() !!}

                </td>
            </tr>
            @endforeach
            </tbody>

        </table>
    </div>


</div>
@endsection
@section('scripts')
<script type="text/javascript">
    var theGrid = null;
    $(document).ready(function () {
        theGrid = $('#thegrid').DataTable({
            "processing": false,
            "serverSide": false,
            "ordering": true,
            "responsive": false
        });
    });

</script>
@endsection